cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('adm/', admin.site.urls),
    path('/', include('waiter.urls', namespace='waiter')),
    path('/', include('orders.urls', namespace='orders')),
    path('/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='myshop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .import views

app_name = 'shop'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id, self.slug])

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='пароль', widget=forms.TextInput(attrs={'class': 'form-control'}))

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm
from .forms import UserLoginForm
from django.contrib import messages

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

def registration(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы Успешно зарегистрировались!')
            return redirect ('shop:login')
        else:
            messages.error(request, 'Ошибка регистрации, ну тут наши полномочия всё')
    else:
        form = UserCreationForm()
    return render(request, 'shop/registration.html', {"form":form})

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('shop:product_list')
    else:
        form = UserLoginForm
    return render(request, 'shop/login.html', {"form": form})

def user_logout(request):
    logout(request)
    return redirect('login')

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <a href="/" class="logo">My shop</a>
</div>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-4 col-md-8 mx-auto">
      {% if request.user.is_authenticated %}
      <a class="nav-link px-3" href="#">Добро пожаловать, {{ user.username }}</a>| <a class="nav-link px-3" href="{% url 'shop:logout' %}">Выход</a>
      {% else %}
      <a class="nav-link px-3" href="{% url 'shop:login' %}">Войти</a>
      <a class="nav-link px-3" href="{% url 'shop:registration' %}">Регистрация</a>
      {% endif %}
    </div>
</div>
<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
               Your cart:
                <a href="{% url 'cart:cart_detail' %}">
                   {{ total_items }} item{{ total_items|pluralize }},
                    ${{ cart.get_total_price }}
                </a>
            {% else %}
                Your cart is empty.
            {% endif %}
        {% endwith %}
</div>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

shop/templates/shop/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Login</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-block">Логин</button>
</form>
<center>«Кроваво-черное ничто взмесило

Систему тел, спряженных в глуби тел,

Спряженных в глуби тем, там, в темноте

Спряженных тоже. Явственно до жути

Передо мной ударила из мути

Фонтана белоснежного струя.»<center>
</body>
</html>

shop/templates/shop/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ну теперь наши полномочия точно всё</title>
</head>
<body>

</body>
</html>

shop/templates/shop/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

        {% if messages %}

    {%for message in messages %}

      {% if message.tags == 'error' %}
          <div class="alert alert-danger" role="alert">
            {{ message }}
          </div>
      {% else %}
          <div class="alert alert-{{ message.tags }}" role="alert">
          </div>
      {% endif %}
    {% endfor %}

    {% endif %}
  </div>
</head>
<body>
<h1>Регистрация</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-block">Регистрация</button>
</form>
</body>
</html>